sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: za123456

  alioss:
    bucket-name: bucket-name
    access-key-secret: access-key-secret
    access-key-id: access-key-id
    endpoint: endpoint

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wx04c5a1fc0d2e0504
    secret: fcb3484bc434476958b1873d13d18293
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:


